### ISSUE TITLE
BUG | none srd domain syntax in datasets

### ISSUE THREAD

**Issue by spirillen** [Phishing-Database/dev-center#13]
### What is the problem you are experiencing?

I am experiencing a problem where...
As I'm working on my search script I come a cross the following data in `phishing_database/phishing.database/domain.csv:T.me` 

I believe this should be ensured all records are rfc compliant.

### How can we reproduce the problem?

To reproduce the problem:

1.
2.
3.
4.

### Do you have a screenshot?

<details><summary>Screenshot</summary>
</details>

### What did you expect to happen?

I expected that...

### Is there a workaround?

I found a workaround...

### Additional context

I would like to add...

### Log information

<details><summary>Click to expand</summary>

```
Paste your log file here between the back tics.
```

</details>

**Comment by funilrys** [comment]
I can make every domains lowercase, but please look at the 4§ in page 10 of https://www.ietf.org/rfc/rfc1034.txt ... 🙄

**Comment by spirillen** [comment]
Hehe, yeah it says the DNS should permit mixed case and none lowercase, not the same as uppercase are the right thing 😉  And one major recursor actually fails to be rfc compliant, as it can't handle uppercase/mixedcase...

So year, lowercase all is the right thing to do, also to avoid dubles
